### ISSUE TITLE
Question: why scale by mean in 1-Bit SGD?

### ISSUE THREAD

**Issue by amitport** [afshinabdi/DistributedTraining-QCS#1]
I don't see where in the paper they mention this scaling: https://github.com/afshinabdi/DistributedTraining-QCS/blob/425977554ed3733550569d0d0e701be99d16d512/QuantizerTest/models/quantizers/onebit_quantizer.py#L61

Could you possibly point to where this is described?

Thank you in any case for publishing this

**Comment by afshinabdi** [comment]
This is implicitly mentioned in the first paragraph at page 3:
“For our 1-bit implementation, we find that using a constant quantization threshold of 0 is a good (and cheap) choice,
whereas the reconstruction values used by the unquantizer are tied within each weight-matrix column. The
two values per column are recomputed as to minimize the square quantization error and transmitted in each data exchange.”

Minimizing square quantization error is achieved by taking the mean of the positive and negative values.

**Comment by amitport** [comment]
@afshinabdi thanks! I wish such papers were a little less implicit 🙂
